name: Golden Plains Baptist Church
title: Golden Plains Baptist Church

url: https://jocefr.github.io
baseurl: /GPBCWebsite/

sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
 - working_files